### PR TITLE
NL Language support

### PR DESCRIPTION
**Pull request by picanl**
Hi Thomas, 

Tried to add NL language support, i'm not sure if i have correctly edited all necessary files 

Please check it if you want. 

best regards, 

Nick

### CODE REVIEW

**Comment by picanl** [comment]
check if tabs and comma's are correct please

**Comment by tmunzer** [comment]
Hi Nick,

I change the var name in the translation files (from "en" to "nl").
I'll also add the code to load the i18n file in the view files.

For the rest, all seems to be correct :)

**Comment by tmunzer** [comment]
done

**Comment by picanl** [comment]
Hi thomas,
Did you test it? 
Is there a way in config to set default language?
--
Verstuurd via de myMail-app voor Android donderdag, 16 augustus 2018, 06:22p.m. +02:00 van Thomas Munzer  notifications@github.com :

**Comment by tmunzer** [comment]
Yes, I tested it quickly (at least the login page).
The app is using the web browser language to choose which language to display. 

There is also the button on the top right corner, which allows to change the display language, but I'll have to add the Dutch option here...

If you want to test, the docker image is build. So you can just update your app, and you should see your work on the screen! :)

**Comment by tmunzer** [comment]
I just added the Dutch button selector. The new image will be ready in 15min.

**Comment by picanl** [comment]
Nice :) lets test it out.
If you tell me the file i will add the "dutch" button 
--
Verstuurd via de myMail-app voor Android donderdag, 16 augustus 2018, 06:47p.m. +02:00 van Thomas Munzer  notifications@github.com :

**Comment by picanl** [comment]
Lol just  mailed you it haha 
Great work thanks.
--
Verstuurd via de myMail-app voor Android donderdag, 16 augustus 2018, 06:54p.m. +02:00 van Thomas Munzer  notifications@github.com :

**Comment by tmunzer** [comment]
Yes, I saw that... :)
It wasn't a big change, so it didn't took too much time!

**Comment by picanl** [comment]
Updating now :)
Oh just to inform you, had issue yesterday with ACS, it failed to refresh token.. Had to manually create a new access key to get it working again.. Key had expired status in HM NG maybe thats why?
--
Verstuurd via de myMail-app voor Android donderdag, 16 augustus 2018, 06:58p.m. +02:00 van Thomas Munzer  notifications@github.com :

**Comment by tmunzer** [comment]
Good question. I may have to validate this point...

**Pull request merged**
